# Putong OJ Docker Compose Configuration
# You should mount the data, logs and uploads directories to persist data.

services:
  putong-oj:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - PTOJ_MONGODB_URL=mongodb://db:27017/oj
      - PTOJ_REDIS_URL=redis://redis:6379
      - PTOJ_SANDBOX_ENDPOINT=http://sandbox:5050
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - putong-oj-data:/app/data
      - putong-oj-uploads:/app/public/uploads
    depends_on:
      - redis
      - db
      - sandbox

  db:
    image: mongo:latest
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  sandbox:
    build:
      context: .
      dockerfile: apps/tasks/Dockerfile.sandbox
    privileged: true
    shm_size: 256m
    volumes:
      - putong-oj-data:/app/data:ro

volumes:
  putong-oj-data:
  putong-oj-uploads:
