// session
export const TRIGGER_LOGIN = 'TRIGGER_LOGIN'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SHOW_LOGIN = 'SHOW_LOGIN'
export const SHOW_REGISTER = 'SHOW_REGISTER'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

// problem
export const GET_PROBLEM = 'GET_PROBLEM'
export const GET_PROBLEM_LIST = 'GET_PROBLEM_LIST'
export const GET_PROBLEM_SOLVED = 'GET_PROBLEM_SOLVED'
export const GET_SUM_PROBLEM = 'GET_SUM_PROBLEM'
export const UPDATE_PROBLEM = 'UPDATE_PROBLEM'
export const DELETE_PROBLEM = 'DELETE_PROBLEM'

// news
export const UPDATE_NEWS = 'UPDATE_NEWS'
export const UPDATE_NEW_LIST = 'UPDATE_NEW_LIST'
export const UPDATE_NEWS_SUM = 'UPDATE_NEWS_SUM'
export const DELETE_NEWS = 'DELETE_NEWS'

// solution
export const GET_SOLUTION = 'GET_SOLUTION'
export const UPDATE_SOLUTION_LIST = 'UPDATE_SOLUTION_LIST'
export const UPDATE_SUM_SOLUTIONS = 'UPDATE_SUM_SOLUTIONS'

// user
export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST'
export const UPDATE_USERS_ADMIN_LIST = 'UPDATE_USERS_ADMIN_LIST'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_SOLVED = 'UPDATE_SOLVED'
export const UPDATE_UNSOLVED = 'UPDATE_UNSOLVED'
export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP'
export const UPDATE_STATISTICS_LIST = 'UPDATE_STATISTICS_LIST'
export const UPDATE_COUNT_LIST = 'UPDATE_COUNT_LIST'
export const UPDATE_STATISTICS_TOTAL = 'UPDATE_STATISTICS_TOTAL'
export const UPDATE_STATISTICS_TABLE = 'UPDATE_STATISTICS_TABLE'
export const UPDATE_STATISTICS_CHARTS = 'UPDATE_STATISTICS_CHARTS'

// ranklist
export const UPDATE_RANKLIST = 'UPDATE_RANKLIST'
export const UPDATE_SUM_RANKLIST = 'UPDATE_SUM_RANKLIST'

// contest
export const UPDATE_CONTEST_LIST = 'UPDATE_CONTEST_LIST'
export const UPDATE_SUM_CONTEST = 'UPDATE_SUM_CONTEST'
export const GET_CONTEST = 'GET_CONTEST'
export const GET_CONTEST_OVERVIEW = 'GET_CONTEST_OVERVIEW'
export const GET_CONTEST_SOLVED = 'GET_CONTEST_SOLVED'
export const GET_CONTEST_TOTAL_PRO = 'GET_CONTEST_TOTAL_PRO'
export const GET_CONTEST_RANK = 'GET_CONTEST_RANK'
export const DELETE_CONTEST = 'DELETE_CONTEST'

// group
export const UPDATE_GROUP = 'UPDATE_GROUP'
export const UPDATE_GROUP_LIST = 'UPDATE_GROUP_LIST'
export const DELETE_GROUP = 'DELETE_GROUP'

// testcase
export const UPDATE_TESTCASE = 'UPDATE_TESTCASE'
export const UPDATE_TESTCASE_LIST = 'UPDATE_TESTCASE_LIST'
export const DELETE_TESTCASE = 'DELETE_TESTCASE'

// tag
export const UPDATE_TAG = 'UPDATE_TAG'
export const UPDATE_TAG_LIST = 'UPDATE_TAG_LIST'

// index
export const SET_SERVERTIME = 'SET_SERVERTIME'
export const UPDATE_SERVERTIME = 'UPDATE_SERVERTIME'
export const SET_WEBSITE_CONFIG = 'SET_WEBSITE_CONFIG'
