export type {
  CommentEntity,
  ContestEntity,
  CourseEntity,
  CourseMemberEntity,
  CourseProblemEntity,
  CourseRole,
  DiscussionEntity,
  FileEntity,
  GroupEntity,
  OAuthConnectionEntity,
  ProblemEntity,
  SubmissionEntity,
  TagEntity,
  UserEntity,
} from '@putongoj/shared'
