name: Code Sandbox

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - apps/tasks/Dockerfile.sandbox
      - .github/workflows/sandbox.yml
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Aliyun Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v4
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: registry.cn-hangzhou.aliyuncs.com/putong-oj/ptoj-sandbox
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build sandbox image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: apps/tasks/Dockerfile.sandbox
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
